'use server'

// src/lib/actions/team.ts
// =============================================================================
// LUSTRE — Team Management Server Actions
// =============================================================================

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { sendInvitationEmail } from '@/lib/email'

// -----------------------------------------------------------------------------
// Invite a team member
// -----------------------------------------------------------------------------

export type InviteState = { error?: string; success?: boolean }

export async function inviteTeamMember(
  prevState: InviteState,
  formData: FormData
): Promise<InviteState> {
  const email = (formData.get('email') as string)?.trim().toLowerCase()
  const role  = formData.get('role') as string

  if (!email) return { error: 'Please enter an email address.' }
  if (!email.includes('@')) return { error: 'Please enter a valid email address.' }
  if (!['admin', 'team_member'].includes(role)) return { error: 'Invalid role selected.' }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  // Verify caller is an admin
  const { data: profile } = await supabase
    .from('profiles')
    .select('organisation_id, role, full_name')
    .eq('id', user.id)
    .single()

  if (!profile || profile.role !== 'admin') {
    return { error: 'Only admins can invite team members.' }
  }

  // Fetch org name for the email
  const { data: org } = await supabase
    .from('organisations')
    .select('name')
    .eq('id', profile.organisation_id)
    .single()

  if (!org) return { error: 'Organisation not found.' }

  // Check for an existing active (pending) invitation for this email
  const { data: existing } = await supabase
    .from('invitations')
    .select('id')
    .eq('organisation_id', profile.organisation_id)
    .eq('email', email)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .single()

  if (existing) {
    return { error: 'An active invitation for this email already exists.' }
  }

  // Create the invitation row (token is generated by DB default)
  const { data: invitation, error: insertError } = await supabase
    .from('invitations')
    .insert({
      organisation_id: profile.organisation_id,
      email,
      role,
      invited_by: user.id,
    })
    .select('token, expires_at')
    .single()

  if (insertError || !invitation) {
    console.error('Invitation insert error:', insertError)
    return { error: 'Failed to create invitation. Please try again.' }
  }

  // Send the invitation email
  const acceptUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite/${invitation.token}`
  const { error: emailError } = await sendInvitationEmail({
    inviteeEmail: email,
    inviterName:  profile.full_name,
    orgName:      org.name,
    role,
    acceptUrl,
    expiresAt:    invitation.expires_at,
  })

  if (emailError) {
    // Roll back the invitation if email failed to send
    await supabase.from('invitations').delete().eq('token', invitation.token)
    return { error: 'Failed to send invitation email. Please try again.' }
  }

  return { success: true }
}

// -----------------------------------------------------------------------------
// Revoke a pending invitation
// -----------------------------------------------------------------------------

export async function revokeInvitation(id: string): Promise<{ error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  // RLS enforces admin-only delete — just attempt the delete
  const { error } = await supabase
    .from('invitations')
    .delete()
    .eq('id', id)
    .is('accepted_at', null)   // only revoke pending invitations

  if (error) {
    console.error('Revoke invitation error:', error)
    return { error: 'Failed to revoke invitation.' }
  }

  return {}
}

// -----------------------------------------------------------------------------
// Accept an invitation
// Called from /invite/[token] — user must already be authenticated.
// Delegates to a SECURITY DEFINER function that moves the user's profile
// to the invited org and cleans up the auto-created empty org.
// -----------------------------------------------------------------------------

export async function acceptInvitation(token: string): Promise<{ error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect(`/login?redirect=/invite/${token}`)

  const { data, error } = await supabase.rpc('accept_invitation', { p_token: token })

  if (error) {
    console.error('accept_invitation RPC error:', error)
    return { error: 'Failed to accept invitation. Please try again.' }
  }

  const result = data as { success?: boolean; error?: string }
  if (result?.error) return { error: result.error }

  redirect('/dashboard')
  // redirect() throws — this line is never reached but satisfies the type checker
  return {}
}
