'use server'

// src/lib/actions/team.ts
// =============================================================================
// LUSTRE — Team Management Server Actions
// =============================================================================

import { redirect }         from 'next/navigation'
import { requireAdmin, getOrgAndUser } from './_auth'
import { logAuditEvent }    from '@/lib/audit'
import { sendInvitationEmail } from '@/lib/email'

// -----------------------------------------------------------------------------
// Invite a team member
// -----------------------------------------------------------------------------

export type InviteState = { error?: string; success?: boolean }

export async function inviteTeamMember(
  prevState: InviteState,
  formData: FormData
): Promise<InviteState> {
  const email = (formData.get('email') as string)?.trim().toLowerCase()
  const role  = formData.get('role') as string

  if (!email) return { error: 'Please enter an email address.' }
  if (!email.includes('@')) return { error: 'Please enter a valid email address.' }
  if (!['admin', 'team_member'].includes(role)) return { error: 'Invalid role selected.' }

  let ctx
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Only admins can invite team members.' }
  }

  const { supabase, orgId, userId } = ctx

  // Fetch the admin's name + org name for the email
  const [{ data: profile }, { data: org }] = await Promise.all([
    supabase.from('profiles').select('full_name').eq('id', userId).single(),
    supabase.from('organisations').select('name').eq('id', orgId).single(),
  ])

  if (!org) return { error: 'Organisation not found.' }

  // Check for an existing active (pending) invitation for this email
  const { data: existing } = await supabase
    .from('invitations')
    .select('id')
    .eq('organisation_id', orgId)
    .eq('email', email)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .single()

  if (existing) {
    return { error: 'An active invitation for this email already exists.' }
  }

  // Create the invitation row (token generated by DB default)
  const { data: invitation, error: insertError } = await supabase
    .from('invitations')
    .insert({ organisation_id: orgId, email, role, invited_by: userId })
    .select('token, expires_at')
    .single()

  if (insertError || !invitation) {
    console.error('Invitation insert error:', insertError)
    return { error: 'Failed to create invitation. Please try again.' }
  }

  // Send the invitation email
  const acceptUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite/${invitation.token}`
  const { error: emailError } = await sendInvitationEmail({
    inviteeEmail: email,
    inviterName:  profile?.full_name ?? 'A team member',
    orgName:      org.name,
    role,
    acceptUrl,
    expiresAt:    invitation.expires_at,
  })

  if (emailError) {
    // Roll back the invitation if the email failed
    await supabase.from('invitations').delete().eq('token', invitation.token)
    return { error: 'Failed to send invitation email. Please try again.' }
  }

  await logAuditEvent(supabase, {
    orgId,
    actorId:      userId,
    action:       'invite_team_member',
    resourceType: 'invitation',
    metadata:     { email, role },
  })

  return { success: true }
}

// -----------------------------------------------------------------------------
// Revoke a pending invitation
// -----------------------------------------------------------------------------

export async function revokeInvitation(id: string): Promise<{ error?: string }> {
  let ctx
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Only admins can revoke invitations.' }
  }

  const { supabase, orgId, userId } = ctx

  const { error } = await supabase
    .from('invitations')
    .delete()
    .eq('id', id)
    .eq('organisation_id', orgId)   // belt-and-suspenders alongside RLS
    .is('accepted_at', null)

  if (error) {
    console.error('Revoke invitation error:', error)
    return { error: 'Failed to revoke invitation.' }
  }

  await logAuditEvent(supabase, {
    orgId,
    actorId:      userId,
    action:       'revoke_invitation',
    resourceType: 'invitation',
    resourceId:   id,
  })

  return {}
}

// -----------------------------------------------------------------------------
// Accept an invitation
// Called from /invite/[token] — user must already be authenticated.
// Delegates to a SECURITY DEFINER function that moves the user's profile
// to the invited org and cleans up their auto-created empty org.
// -----------------------------------------------------------------------------

export async function acceptInvitation(token: string): Promise<{ error?: string }> {
  const { supabase } = await getOrgAndUser()

  const { data, error } = await supabase.rpc('accept_invitation', { p_token: token })

  if (error) {
    console.error('accept_invitation RPC error:', error)
    return { error: 'Failed to accept invitation. Please try again.' }
  }

  const result = data as { success?: boolean; error?: string }
  if (result?.error) return { error: result.error }

  redirect('/dashboard')
  // redirect() throws — this line is never reached but satisfies the type checker
  return {}
}
