'use server'

// src/lib/actions/team.ts
// =============================================================================
// LUSTRE — Team Management Server Actions
// =============================================================================

import { redirect }         from 'next/navigation'
import { requireAdmin, getOrgAndUser } from './_auth'
import { logAuditEvent }    from '@/lib/audit'
import { sendInvitationEmail } from '@/lib/email'
import { PLANS } from '@/lib/stripe/plans'
import type { Plan } from '@/lib/types'

/** Max seats per plan. Free/trial gets starter-equivalent (3). Enterprise is unlimited. */
const SEAT_LIMITS: Record<Plan, number> = {
  free:         3,
  starter:      PLANS.starter.seats,
  professional: PLANS.professional.seats,
  business:     PLANS.business.seats,
  enterprise:   Infinity,
}

// -----------------------------------------------------------------------------
// Invite a team member
// -----------------------------------------------------------------------------

export type InviteState = { error?: string; success?: boolean }

export async function inviteTeamMember(
  prevState: InviteState,
  formData: FormData
): Promise<InviteState> {
  const email = (formData.get('email') as string)?.trim().toLowerCase()
  const role  = formData.get('role') as string

  if (!email) return { error: 'Please enter an email address.' }
  if (!email.includes('@')) return { error: 'Please enter a valid email address.' }
  if (!['admin', 'team_member'].includes(role)) return { error: 'Invalid role selected.' }

  let ctx
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Only admins can invite team members.' }
  }

  const { supabase, orgId, userId } = ctx

  // Fetch the admin's name + org name for the email
  const [{ data: profile }, { data: org }] = await Promise.all([
    supabase.from('profiles').select('full_name').eq('id', userId).single(),
    supabase.from('organisations').select('name').eq('id', orgId).single(),
  ])

  if (!org) return { error: 'Organisation not found.' }

  // Check the email isn't already a member of this org
  const { data: existingMember } = await supabase
    .from('profiles')
    .select('id')
    .eq('organisation_id', orgId)
    .ilike('email', email)
    .maybeSingle()

  if (existingMember) {
    return { error: 'This person is already a member of your team.' }
  }

  // Check for an existing active (pending) invitation for this email
  const { data: existing } = await supabase
    .from('invitations')
    .select('id')
    .eq('organisation_id', orgId)
    .eq('email', email)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .single()

  if (existing) {
    return { error: 'An active invitation for this email already exists.' }
  }

  // Enforce seat limit for the org's current plan
  const [{ data: currentMembers }, { data: pendingInvites }, { data: orgPlan }] = await Promise.all([
    supabase.from('profiles').select('id', { count: 'exact' }).eq('organisation_id', orgId),
    supabase.from('invitations')
      .select('id', { count: 'exact' })
      .eq('organisation_id', orgId)
      .is('accepted_at', null)
      .gt('expires_at', new Date().toISOString()),
    supabase.from('organisations').select('plan').eq('id', orgId).single(),
  ])

  const plan = (orgPlan?.plan ?? 'free') as Plan
  const seatLimit = SEAT_LIMITS[plan] ?? 3
  const totalOccupied = (currentMembers?.length ?? 0) + (pendingInvites?.length ?? 0)

  if (totalOccupied >= seatLimit) {
    const limitLabel = seatLimit === Infinity ? 'unlimited' : String(seatLimit)
    const planName = plan === 'free' ? 'free trial' : plan
    return {
      error: `Your ${planName} plan includes up to ${limitLabel} seats. Upgrade to add more team members.`,
    }
  }

  // Create the invitation row (token generated by DB default)
  const { data: invitation, error: insertError } = await supabase
    .from('invitations')
    .insert({ organisation_id: orgId, email, role, invited_by: userId })
    .select('token, expires_at')
    .single()

  if (insertError || !invitation) {
    console.error('Invitation insert error:', insertError)
    return { error: 'Failed to create invitation. Please try again.' }
  }

  // Send the invitation email
  const acceptUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite/${invitation.token}`
  const { error: emailError } = await sendInvitationEmail({
    inviteeEmail: email,
    inviterName:  profile?.full_name ?? 'A team member',
    orgName:      org.name,
    role,
    acceptUrl,
    expiresAt:    invitation.expires_at,
  })

  if (emailError) {
    // Roll back the invitation if the email failed
    await supabase.from('invitations').delete().eq('token', invitation.token)
    return { error: 'Failed to send invitation email. Please try again.' }
  }

  await logAuditEvent(supabase, {
    orgId,
    actorId:      userId,
    action:       'invite_team_member',
    resourceType: 'invitation',
    metadata:     { email, role },
  })

  return { success: true }
}

// -----------------------------------------------------------------------------
// Revoke a pending invitation
// -----------------------------------------------------------------------------

export async function revokeInvitation(id: string): Promise<{ error?: string }> {
  let ctx
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Only admins can revoke invitations.' }
  }

  const { supabase, orgId, userId } = ctx

  const { error } = await supabase
    .from('invitations')
    .delete()
    .eq('id', id)
    .eq('organisation_id', orgId)   // belt-and-suspenders alongside RLS
    .is('accepted_at', null)

  if (error) {
    console.error('Revoke invitation error:', error)
    return { error: 'Failed to revoke invitation.' }
  }

  await logAuditEvent(supabase, {
    orgId,
    actorId:      userId,
    action:       'revoke_invitation',
    resourceType: 'invitation',
    resourceId:   id,
  })

  return {}
}

// -----------------------------------------------------------------------------
// Remove a member from the organisation
// Guards: caller must be admin; cannot remove yourself;
//         cannot remove the last admin.
// -----------------------------------------------------------------------------

export async function removeMember(profileId: string): Promise<{ error?: string }> {
  let ctx
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Only admins can remove team members.' }
  }

  const { supabase, orgId, userId } = ctx

  if (profileId === userId) {
    return { error: 'You cannot remove yourself from the team.' }
  }

  // Ensure removing this person won't leave the org without an admin
  const { data: admins } = await supabase
    .from('profiles')
    .select('id')
    .eq('organisation_id', orgId)
    .eq('role', 'admin')

  const targetIsAdmin = admins?.some(a => a.id === profileId)
  if (targetIsAdmin && (admins?.length ?? 0) <= 1) {
    return { error: 'Cannot remove the only admin. Promote another member first.' }
  }

  const { error } = await supabase
    .from('profiles')
    .delete()
    .eq('id', profileId)
    .eq('organisation_id', orgId) // belt-and-suspenders

  if (error) {
    console.error('removeMember error:', error)
    return { error: 'Failed to remove member. Please try again.' }
  }

  await logAuditEvent(supabase, {
    orgId,
    actorId:      userId,
    action:       'remove_member',
    resourceType: 'profile',
    resourceId:   profileId,
  })

  return {}
}

// -----------------------------------------------------------------------------
// Update a member's role
// Guards: caller must be admin; cannot demote yourself if last admin.
// -----------------------------------------------------------------------------

export async function updateMemberRole(
  profileId: string,
  newRole: string
): Promise<{ error?: string }> {
  if (!['admin', 'team_member'].includes(newRole)) {
    return { error: 'Invalid role.' }
  }

  let ctx
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Only admins can change member roles.' }
  }

  const { supabase, orgId, userId } = ctx

  // Prevent demoting yourself if you're the last admin
  if (profileId === userId && newRole !== 'admin') {
    const { data: admins } = await supabase
      .from('profiles')
      .select('id')
      .eq('organisation_id', orgId)
      .eq('role', 'admin')
    if ((admins?.length ?? 0) <= 1) {
      return { error: 'Cannot demote yourself — you are the only admin.' }
    }
  }

  const { error } = await supabase
    .from('profiles')
    .update({ role: newRole })
    .eq('id', profileId)
    .eq('organisation_id', orgId)

  if (error) {
    console.error('updateMemberRole error:', error)
    return { error: 'Failed to update role. Please try again.' }
  }

  await logAuditEvent(supabase, {
    orgId,
    actorId:      userId,
    action:       'update_member_role',
    resourceType: 'profile',
    resourceId:   profileId,
    metadata:     { new_role: newRole },
  })

  return {}
}

// -----------------------------------------------------------------------------
// Accept an invitation
// Called from /invite/[token] — user must already be authenticated.
// Delegates to a SECURITY DEFINER function that moves the user's profile
// to the invited org and cleans up their auto-created empty org.
// -----------------------------------------------------------------------------

export async function acceptInvitation(token: string): Promise<{ error?: string }> {
  const { supabase } = await getOrgAndUser()

  const { data, error } = await supabase.rpc('accept_invitation', { p_token: token })

  if (error) {
    console.error('accept_invitation RPC error:', error)
    return { error: 'Failed to accept invitation. Please try again.' }
  }

  const result = data as { success?: boolean; error?: string }
  if (result?.error) return { error: result.error }

  redirect('/dashboard')
  // redirect() throws — this line is never reached but satisfies the type checker
  return {}
}
